### ISSUE TITLE
Adding links raises DOMException

### ISSUE THREAD

**Issue by wizpig64** [heyscrumpy/tiptap#33]
Hello,

I'm trying to use tiptap as the editor for a personal wiki project, and I'm having trouble getting links to insert. I've copied the code right out of the Links example (and then moved it from menububble to menubar, but this is not the issue), but something deep in prosemirror raises an exception when trying to manipulate the DOM.

Here's my cleaned up source code dumped into a fresh vue-cli environment: https://github.com/wizpig64/vue-wiki-test (see `src/components/Editor.vue` and `EditorMenubar.vue`)

And a live demo: https://wiki.wizpig64.com/

Here's the traceback provided by chrome when trying to add a link:
```
index.js?703f:1293 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': This node type does not support this method.
    at renderDescs (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1293:17)
    at renderDescs (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1297:7)
    at NodeViewDesc.renderChildren (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1102:5)
    at NodeViewDesc.updateChildren (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1098:64)
    at NodeViewDesc.updateInner (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1120:33)
    at NodeViewDesc.update (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1112:10)
    at ViewTreeUpdater.updateNextNode (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1498:14)
    at eval (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1087:17)
    at iterDeco (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1573:7)
    at NodeViewDesc.updateChildren (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1072:5)
```

Edit: In firefox it's a HierarchyRequestError:

```
HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy    index.js:1293
renderDescs                                      index.js:1293
renderDescs                                      index.js:1297
renderChildren                                   index.js:1102
updateChildren                                   index.js:1098
updateInner                                      index.js:1120
update                                           index.js:1112
updateNextNode                                   index.js:1498
updateChildren/<                                 index.js:1087
iterDeco                                         index.js:1573
updateChildren                                   index.js:1072
updateInner                                      index.js:1120
update                                           index.js:1112
updateState                                      index.js:4250
dispatchTransaction                              tiptap.esm.js:766
dispatchTransaction self-hosted:987:17 dispatch  index.js:4465
dispatch self-hosted:987:17 updateMark/<         commands.esm.js:194
commands/</obj[name]                             tiptap.esm.js:383
setLinkUrl                                       EditorMenubar.vue:108
setLinkUrl self-hosted:991:17 submit             EditorMenubar.vue:147
invoker                                          vue.runtime.esm.js:2023
withMacroTask/fn._withTask                       vue.runtime.esm.js:1822
```

I don't get the same error when running the Links example, but as a newbie javascript developer, I guess I just don't know what I'm doing wrong at this point.

Thanks for any advice you can give!

**Comment by philippkuehn** [comment]
Hey there is another error message in my console

```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)
```

The link mark used a nodeView rendered as a vue component. That wasn't needed at all. I removed this in a new version of `tiptap-extensions`. But if you want to use nodes or marks as vue components later, you may have to install `vue-template-compiler`.

**Comment by wizpig64** [comment]
Just wanted to say this did fix my issue, thanks!

I was getting the runtime-only error whether or I imported from 'vue/dist/vue' or not. But now after the tiptap update I can say the full vue import is required.
